<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [X2Go-User] X2Go-User Non-Digest, Vol 38, Issue 26
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/x2go-user/2013-October/index.html" >
   <LINK REL="made" HREF="mailto:x2go-user%40lists.berlios.de?Subject=Re%3A%20%5BX2Go-User%5D%20X2Go-User%20Non-Digest%2C%20Vol%2038%2C%20Issue%2026&In-Reply-To=%3C527243A4.7000005%40gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="001737.html">
   <LINK REL="Next"  HREF="001739.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[X2Go-User] X2Go-User Non-Digest, Vol 38, Issue 26</H1>
    <B>Ted Barnes</B> 
    <A HREF="mailto:x2go-user%40lists.berlios.de?Subject=Re%3A%20%5BX2Go-User%5D%20X2Go-User%20Non-Digest%2C%20Vol%2038%2C%20Issue%2026&In-Reply-To=%3C527243A4.7000005%40gmail.com%3E"
       TITLE="[X2Go-User] X2Go-User Non-Digest, Vol 38, Issue 26">madogdevelopment at gmail.com
       </A><BR>
    <I>Thu Oct 31 12:48:52 CET 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="001737.html">[X2Go-User] session broker setup (was: Re:  X2Go-User Digest, Vol 38, Issue 25)
</A></li>
        <LI>Next message: <A HREF="001739.html">[X2Go-User] X2Go-User Non-Digest, Vol 38, Issue 26
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1738">[ date ]</a>
              <a href="thread.html#1738">[ thread ]</a>
              <a href="subject.html#1738">[ subject ]</a>
              <a href="author.html#1738">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi Mike:

How are you?  Another update...hope am making progress, but not there 
yet.  Let me know if it would help to send over copies of 
x2gobroker.conf and the other configs?

Is it the case I am using the wrong backend, and don't know how to set 
it to backend inifile?  Thanks for the help(!)

1)  Rebuilt server (using Squeeze) and incorporated nightly x2go builds

apt-get install -y x2goserver x2goserver-xsession
apt-get install -y x2gobroker-wsgi
apt-get install -y apache2 (apache fails until instill libapache2-mod-wsgi)
apt-get install -y libapache2-mod-wsgi
apt-get install -y x2gobroker-authservice

2)  Checked versions
x2gobroker-wsgi:  0.0.3.0-0~x2go1+squeeze~heuler~20131002~558~build1
x2goserver:  4.1.0.0-0~x2go1+squeeze~heuler~20130731~779~build1
x2gobroker-authservice:  0.0.3.0-0~x2go1+squeeze~heuler~20131002~558~build1

3)  Set backend to inifile
In x2gobroker.conf:
[inifile]
enable = false
session-profiles = /etc/x2go/broker/x2gobroker-sessionprofiles.conf

* have made various tweaks to x2gobroker-sessionprofiles.conf, 
x2gobroker.conf, and x2gobroker-wsgi.apache.conf - have not touched 
x2gobroker-wsgi.apache.vhost without noticeable difference in outcome.

4)  When try to connect:
Not sure this matters, but on client get:
x2go-INFO-1&gt; &quot;Starting x2goclient...&quot;
x2go-WARNING-1&gt; &quot;Can't load translator: :/x2goclient_en_us&quot;
x2go-WARNING-2&gt; &quot;Can't load translator: :/qt_en_US&quot;

And...

SSH - says inifile not enabled....(when try to connect first time, does 
ask if I want to trust key and creates known hosts file)

x2goclient --broker-url=&quot;<A HREF="ssh://user@xxx.xxx.xxx.xxx/usr/bin/x2gobroker">ssh://user@xxx.xxx.xxx.xxx/usr/bin/x2gobroker</A> 
--backend=inifile&quot;

2013-10-31 07:00:32,777 - broker - INFO - X2Go Session Broker (0.0.3.0),
2013-10-31 07:00:32,786 - broker - INFO -   written by Mike Gabriel 
(X2Go Project) &lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
2013-10-31 07:00:32,789 - broker - INFO - Setting up the broker's 
environment...
2013-10-31 07:00:32,790 - broker - INFO -   X2GOBROKER_DEBUG: True
2013-10-31 07:00:32,790 - broker - INFO -   X2GOBROKER_CONFIG: 
/etc/x2go/x2gobroker.conf
2013-10-31 07:00:32,790 - broker - INFO -   X2GOBROKER_AGENT_CMD: 
/usr/lib/x2go/x2gobroker-agent
2013-10-31 07:00:32,790 - broker - INFO -   
X2GOBROKER_AUTHSERVICE_SOCKET: /run/x2gobroker/x2gobroker-authservice.socket
2013-10-31 07:00:32,790 - broker - INFO -   X2GOBROKER_DEFAULT_BACKEND: 
zeroconf
2013-10-31 07:00:32,790 - broker - INFO -   X2GOBROKER_SSL_CERTFILE:
2013-10-31 07:00:32,791 - broker - INFO -   X2GOBROKER_SSL_KEYFILE:
2013-10-31 07:00:33,039 - broker - ERROR - broker backend ,,inifile'' is 
disabled on this system

When try HTTP, get &quot;Error Login failed!  Please try again&quot;


5)  Some log output

---------------------------authservice.log
2013-10-30 18:04:56,904 - authservice - INFO - X2Go Session Broker 
(0.0.3.0), written by Mike Gabriel (X2Go Project) 
&lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
2013-10-30 18:04:56,905 - authservice - INFO - Setting up the PAM 
authentication service's environment...
2013-10-30 18:04:56,905 - authservice - INFO -   X2GOBROKER_DEBUG: False
2013-10-30 18:04:56,905 - authservice - INFO -   
X2GOBROKER_AUTHSERVICE_SOCKET: 
/var/run/x2gobroker/x2gobroker-authservice.socket
2013-10-30 18:24:22,544 - authservice - INFO - X2Go Session Broker 
(0.0.3.0), written by Mike Gabriel (X2Go Project) 
&lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
2013-10-30 18:24:22,550 - authservice - INFO - Setting up the PAM 
authentication service's environment...
2013-10-30 18:24:22,550 - authservice - INFO -   X2GOBROKER_DEBUG: False
2013-10-30 18:24:22,551 - authservice - INFO -   
X2GOBROKER_AUTHSERVICE_SOCKET: 
/var/run/x2gobroker/x2gobroker-authservice.socket
2013-10-30 18:35:29,230 - authservice - INFO - X2Go Session Broker 
(0.0.3.0), written by Mike Gabriel (X2Go Project) 
&lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
2013-10-30 18:35:29,237 - authservice - INFO - Setting up the PAM 
authentication service's environment...
2013-10-30 18:35:29,237 - authservice - INFO -   X2GOBROKER_DEBUG: False
2013-10-30 18:35:29,238 - authservice - INFO -   
X2GOBROKER_AUTHSERVICE_SOCKET: 
/var/run/x2gobroker/x2gobroker-authservice.socket

---------------------broker.log
2013-10-30 18:32:38,025 - broker - INFO - X2Go Session Broker (0.0.3.0),
2013-10-30 18:32:38,030 - broker - INFO -   written by Mike Gabriel 
(X2Go Project) &lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
2013-10-30 18:32:38,030 - broker - INFO - Setting up the broker's 
environment...
2013-10-30 18:32:38,030 - broker - INFO -   X2GOBROKER_DEBUG: False
2013-10-30 18:32:38,030 - broker - INFO -   X2GOBROKER_CONFIG: 
/etc/x2go/x2gobroker.conf
2013-10-30 18:32:38,030 - broker - INFO -   X2GOBROKER_AGENT_CMD: 
/usr/lib/x2go/x2gobroker-agent
2013-10-30 18:32:38,031 - broker - INFO -   
X2GOBROKER_AUTHSERVICE_SOCKET: /run/x2gobroker/x2gobroker-authservice.socket
2013-10-30 18:32:38,031 - broker - INFO -   X2GOBROKER_DEFAULT_BACKEND: 
zeroconf
2013-10-30 18:32:38,031 - broker - INFO -   X2GOBROKER_SSL_CERTFILE:
2013-10-30 18:32:38,031 - broker - INFO -   X2GOBROKER_SSL_KEYFILE:
2013-10-30 18:34:02,981 - broker - INFO - X2Go Session Broker (0.0.3.0),
2013-10-30 18:34:02,981 - broker - INFO -   written by Mike Gabriel 
(X2Go Project) &lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
2013-10-30 18:34:02,981 - broker - INFO - Setting up the broker's 
environment...
2013-10-30 18:34:02,981 - broker - INFO -   X2GOBROKER_DEBUG: False
2013-10-30 18:34:02,982 - broker - INFO -   X2GOBROKER_CONFIG: 
/etc/x2go/x2gobroker.conf
2013-10-30 18:34:02,990 - broker - INFO -   X2GOBROKER_AGENT_CMD: 
/usr/lib/x2go/x2gobroker-agent
2013-10-30 18:34:02,990 - broker - INFO -   
X2GOBROKER_AUTHSERVICE_SOCKET: /run/x2gobroker/x2gobroker-authservice.socket
2013-10-30 18:34:02,990 - broker - INFO -   X2GOBROKER_DEFAULT_BACKEND: 
zeroconf
2013-10-30 18:34:02,990 - broker - INFO -   X2GOBROKER_SSL_CERTFILE:
2013-10-30 18:34:02,990 - broker - INFO -   X2GOBROKER_SSL_KEYFILE:
2013-10-30 18:36:41,065 - broker - INFO - X2Go Session Broker (0.0.3.0),
2013-10-30 18:36:41,090 - broker - INFO -   written by Mike Gabriel 
(X2Go Project) &lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
2013-10-30 18:36:41,090 - broker - INFO - Setting up the broker's 
environment...
2013-10-30 18:36:41,091 - broker - INFO -   X2GOBROKER_DEBUG: False
2013-10-30 18:36:41,091 - broker - INFO -   X2GOBROKER_CONFIG: 
/etc/x2go/x2gobroker.conf
2013-10-30 18:36:41,091 - broker - INFO -   X2GOBROKER_AGENT_CMD: 
/usr/lib/x2go/x2gobroker-agent
2013-10-30 18:36:41,091 - broker - INFO -   
X2GOBROKER_AUTHSERVICE_SOCKET: /run/x2gobroker/x2gobroker-authservice.socket
2013-10-30 18:36:41,091 - broker - INFO -   X2GOBROKER_DEFAULT_BACKEND: 
zeroconf
2013-10-30 18:36:41,091 - broker - INFO -   X2GOBROKER_SSL_CERTFILE:
2013-10-30 18:36:41,091 - broker - INFO -   X2GOBROKER_SSL_KEYFILE:
2013-10-30 18:41:20,430 - broker - INFO - X2Go Session Broker (0.0.3.0),
2013-10-30 18:41:20,430 - broker - INFO -   written by Mike Gabriel 
(X2Go Project) &lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
2013-10-30 18:41:20,430 - broker - INFO - Setting up the broker's 
environment...
2013-10-30 18:41:20,431 - broker - INFO -   X2GOBROKER_DEBUG: False
2013-10-30 18:41:20,431 - broker - INFO -   X2GOBROKER_CONFIG: 
/etc/x2go/x2gobroker.conf
2013-10-30 18:41:20,431 - broker - INFO -   X2GOBROKER_AGENT_CMD: 
/usr/lib/x2go/x2gobroker-agent
2013-10-30 18:41:20,431 - broker - INFO -   
X2GOBROKER_AUTHSERVICE_SOCKET: /run/x2gobroker/x2gobroker-authservice.socket
2013-10-30 18:41:20,431 - broker - INFO -   X2GOBROKER_DEFAULT_BACKEND: 
zeroconf
2013-10-30 18:41:20,431 - broker - INFO -   X2GOBROKER_SSL_CERTFILE:
2013-10-30 18:41:20,431 - broker - INFO -   X2GOBROKER_SSL_KEYFILE:
2013-10-30 19:37:42,084 - broker - INFO - X2Go Session Broker (0.0.3.0),
2013-10-30 19:37:42,084 - broker - INFO -   written by Mike Gabriel 
(X2Go Project) &lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
2013-10-30 19:37:42,084 - broker - INFO - Setting up the broker's 
environment...
2013-10-30 19:37:42,084 - broker - INFO -   X2GOBROKER_DEBUG: False
2013-10-30 19:37:42,084 - broker - INFO -   X2GOBROKER_CONFIG: 
/etc/x2go/x2gobroker.conf
2013-10-30 19:37:42,084 - broker - INFO -   X2GOBROKER_AGENT_CMD: 
/usr/lib/x2go/x2gobroker-agent
2013-10-30 19:37:42,085 - broker - INFO -   
X2GOBROKER_AUTHSERVICE_SOCKET: /run/x2gobroker/x2gobroker-authservice.socket
2013-10-30 19:37:42,085 - broker - INFO -   X2GOBROKER_DEFAULT_BACKEND: 
zeroconf
2013-10-30 19:37:42,085 - broker - INFO -   X2GOBROKER_SSL_CERTFILE:
2013-10-30 19:37:42,085 - broker - INFO -   X2GOBROKER_SSL_KEYFILE:
2013-10-30 19:42:28,903 - broker - INFO - X2Go Session Broker (0.0.3.0),
2013-10-30 19:42:28,904 - broker - INFO -   written by Mike Gabriel 
(X2Go Project) &lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
2013-10-30 19:42:28,904 - broker - INFO - Setting up the broker's 
environment...
2013-10-30 19:42:28,904 - broker - INFO -   X2GOBROKER_DEBUG: False
2013-10-30 19:42:28,904 - broker - INFO -   X2GOBROKER_CONFIG: 
/etc/x2go/x2gobroker.conf
2013-10-30 19:42:28,904 - broker - INFO -   X2GOBROKER_AGENT_CMD: 
/usr/lib/x2go/x2gobroker-agent
2013-10-30 19:42:28,905 - broker - INFO -   
X2GOBROKER_AUTHSERVICE_SOCKET: /run/x2gobroker/x2gobroker-authservice.socket
2013-10-30 19:42:28,905 - broker - INFO -   X2GOBROKER_DEFAULT_BACKEND: 
zeroconf
2013-10-30 19:42:28,905 - broker - INFO -   X2GOBROKER_SSL_CERTFILE:
2013-10-30 19:42:28,905 - broker - INFO -   X2GOBROKER_SSL_KEYFILE:
2013-10-31 07:02:02,769 - broker - INFO - X2Go Session Broker (0.0.3.0),
2013-10-31 07:02:02,778 - broker - INFO -   written by Mike Gabriel 
(X2Go Project) &lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
2013-10-31 07:02:02,778 - broker - INFO - Setting up the broker's 
environment...
2013-10-31 07:02:02,778 - broker - INFO -   X2GOBROKER_DEBUG: False
2013-10-31 07:02:02,778 - broker - INFO -   X2GOBROKER_CONFIG: 
/etc/x2go/x2gobroker.conf
2013-10-31 07:02:02,778 - broker - INFO -   X2GOBROKER_AGENT_CMD: 
/usr/lib/x2go/x2gobroker-agent
2013-10-31 07:02:02,778 - broker - INFO -   
X2GOBROKER_AUTHSERVICE_SOCKET: /run/x2gobroker/x2gobroker-authservice.socket
2013-10-31 07:02:02,779 - broker - INFO -   X2GOBROKER_DEFAULT_BACKEND: 
zeroconf
2013-10-31 07:02:02,779 - broker - INFO -   X2GOBROKER_SSL_CERTFILE:
2013-10-31 07:02:02,779 - broker - INFO -   X2GOBROKER_SSL_KEYFILE:

-------------------------error.log
2013-10-30 18:32:38,894 - error - ERROR - HTTP request error: HTTP 404: 
Not Found
2013-10-30 18:34:03,439 - error - ERROR - HTTP request error: HTTP 404: 
Not Found
2013-10-30 18:36:41,908 - error - ERROR - HTTP request error: HTTP 404: 
Not Found
2013-10-30 18:41:20,938 - error - ERROR - HTTP request error: HTTP 404: 
Not Found
2013-10-30 19:37:42,566 - error - ERROR - HTTP request error: HTTP 404: 
Not Found
2013-10-30 19:42:29,411 - error - ERROR - HTTP request error: HTTP 404: 
Not Found
2013-10-31 07:02:03,211 - error - ERROR - HTTP request error: HTTP 404: 
Not Found

----------------------------wsgi.log
wsgilog.log: Wed, 30 Oct 2013 18:32:38 ERROR Server got itself in trouble
Traceback (most recent call last):
   File &quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 
179, in __call__
     return self.application(environ, start_response)
   File &quot;/usr/bin/x2gobroker&quot;, line 243, in _application
     return _tornado_application(environ, start_response)
   File &quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in 
__call__
     assert handler._finished
AssertionError
wsgilog.log: Wed, 30 Oct 2013 18:34:03 ERROR Server got itself in trouble
Traceback (most recent call last):
   File &quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 
179, in __call__
     return self.application(environ, start_response)
   File &quot;/usr/bin/x2gobroker&quot;, line 243, in _application
     return _tornado_application(environ, start_response)
   File &quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in 
__call__
     assert handler._finished
AssertionError
wsgilog.log: Wed, 30 Oct 2013 18:36:41 ERROR Server got itself in trouble
Traceback (most recent call last):
   File &quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 
179, in __call__
     return self.application(environ, start_response)
   File &quot;/usr/bin/x2gobroker&quot;, line 243, in _application
     return _tornado_application(environ, start_response)
   File &quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in 
__call__
     assert handler._finished
AssertionError
wsgilog.log: Wed, 30 Oct 2013 18:41:20 ERROR Server got itself in trouble
Traceback (most recent call last):
   File &quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 
179, in __call__
     return self.application(environ, start_response)
   File &quot;/usr/bin/x2gobroker&quot;, line 243, in _application
     return _tornado_application(environ, start_response)
   File &quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in 
__call__
     assert handler._finished
AssertionError
wsgilog.log: Wed, 30 Oct 2013 19:37:42 ERROR Server got itself in trouble
Traceback (most recent call last):
   File &quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 
179, in __call__
     return self.application(environ, start_response)
   File &quot;/usr/bin/x2gobroker&quot;, line 243, in _application
     return _tornado_application(environ, start_response)
   File &quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in 
__call__
     assert handler._finished
AssertionError
wsgilog.log: Wed, 30 Oct 2013 19:42:29 ERROR Server got itself in trouble
Traceback (most recent call last):
   File &quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 
179, in __call__
     return self.application(environ, start_response)
   File &quot;/usr/bin/x2gobroker&quot;, line 243, in _application
     return _tornado_application(environ, start_response)
   File &quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in 
__call__
     assert handler._finished
AssertionError
wsgilog.log: Thu, 31 Oct 2013 07:02:03 ERROR Server got itself in trouble
Traceback (most recent call last):
   File &quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 
179, in __call__
     return self.application(environ, start_response)
   File &quot;/usr/bin/x2gobroker&quot;, line 243, in _application
     return _tornado_application(environ, start_response)
   File &quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in 
__call__
     assert handler._finished
AssertionError

----------------------------access.log (apache)
xxx.xxx.xxx.xxx - - [30/Oct/2013:18:32:37 -0400] &quot;POST 
/x2gobroker/plain/inifile HTTP/1.1&quot; 500 7927 &quot;-&quot; &quot;-&quot;
xxx.xxx.xxx.xxx - - [30/Oct/2013:18:34:02 -0400] &quot;POST 
/x2gobroker/plain/inifile HTTP/1.1&quot; 500 7946 &quot;-&quot; &quot;-&quot;
xxx.xxx.xxx.xxx - - [30/Oct/2013:18:36:40 -0400] &quot;POST 
/x2gobroker/plain/inifile HTTP/1.1&quot; 500 7927 &quot;-&quot; &quot;-&quot;
xxx.xxx.xxx.xxx - - [30/Oct/2013:18:41:20 -0400] &quot;POST 
/x2gobroker/plain/inifile HTTP/1.1&quot; 500 7946 &quot;-&quot; &quot;-&quot;
xxx.xxx.xxx.xxx - - [30/Oct/2013:19:37:41 -0400] &quot;POST 
/x2gobroker/plain/inifile HTTP/1.1&quot; 500 7946 &quot;-&quot; &quot;-&quot;
xxx.xxx.xxx.xxx - - [30/Oct/2013:19:41:21 -0400] &quot;POST 
/cgi-bin/x2gobroker.cgi HTTP/1.1&quot; 404 540 &quot;-&quot; &quot;-&quot;
xxx.xxx.xxx.xxx - - [30/Oct/2013:19:42:28 -0400] &quot;POST 
/x2gobroker/plain/inifile HTTP/1.1&quot; 500 7946 &quot;-&quot; &quot;-&quot;
xxx.xxx.xxx.xxx - - [31/Oct/2013:07:02:02 -0400] &quot;POST 
/x2gobroker/plain/inifile HTTP/1.1&quot; 500 7946 &quot;-&quot; &quot;-&quot;


-----------------------------error.log (apache)
[Wed Oct 30 18:01:12 2013] [notice] Apache/2.2.16 (Debian) mod_wsgi/3.3 
Python/2.6.6 configured -- resuming normal operations
[Wed Oct 30 18:08:05 2013] [notice] caught SIGTERM, shutting down
[Wed Oct 30 18:08:06 2013] [notice] Apache/2.2.16 (Debian) mod_wsgi/3.3 
Python/2.6.6 configured -- resuming normal operations
[Wed Oct 30 18:15:46 2013] [notice] caught SIGTERM, shutting down
[Wed Oct 30 18:15:47 2013] [notice] Apache/2.2.16 (Debian) mod_wsgi/3.3 
Python/2.6.6 configured -- resuming normal operations
[Wed Oct 30 18:21:38 2013] [notice] caught SIGTERM, shutting down
[Wed Oct 30 18:21:39 2013] [notice] Apache/2.2.16 (Debian) mod_wsgi/3.3 
Python/2.6.6 configured -- resuming normal operations
[Wed Oct 30 18:22:51 2013] [notice] caught SIGTERM, shutting down
[Wed Oct 30 18:22:52 2013] [notice] Apache/2.2.16 (Debian) mod_wsgi/3.3 
Python/2.6.6 configured -- resuming normal operations
[Wed Oct 30 18:23:30 2013] [notice] caught SIGTERM, shutting down
[Wed Oct 30 18:24:10 2013] [notice] Apache/2.2.16 (Debian) mod_wsgi/3.3 
Python/2.6.6 configured -- resuming normal operations
[Wed Oct 30 18:28:56 2013] [notice] caught SIGTERM, shutting down
[Wed Oct 30 18:28:57 2013] [notice] Apache/2.2.16 (Debian) mod_wsgi/3.3 
Python/2.6.6 configured -- resuming normal operations
[Wed Oct 30 18:31:33 2013] [notice] caught SIGTERM, shutting down
[Wed Oct 30 18:31:34 2013] [notice] Apache/2.2.16 (Debian) mod_wsgi/3.3 
Python/2.6.6 configured -- resuming normal operations
[Wed Oct 30 18:32:38 2013] [error] wsgilog.log: Wed, 30 Oct 2013 
18:32:38 ERROR Server got itself in trouble
[Wed Oct 30 18:32:38 2013] [error] Traceback (most recent call last):
[Wed Oct 30 18:32:38 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 18:32:38 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 18:32:38 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 18:32:38 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 18:32:38 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 18:32:38 2013] [error]     assert handler._finished
[Wed Oct 30 18:32:38 2013] [error] AssertionError
[Wed Oct 30 18:32:38 2013] [error] Server got itself in trouble
[Wed Oct 30 18:32:38 2013] [error] Traceback (most recent call last):
[Wed Oct 30 18:32:38 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 18:32:38 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 18:32:38 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 18:32:38 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 18:32:38 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 18:32:38 2013] [error]     assert handler._finished
[Wed Oct 30 18:32:38 2013] [error] AssertionError
[Wed Oct 30 18:32:39 2013] [error] /usr/lib/python2.6/cgitb.py:173: 
DeprecationWarning: BaseException.message has been deprecated as of 
Python 2.6
[Wed Oct 30 18:32:39 2013] [error]   value = 
pydoc.html.repr(getattr(evalue, name))
[Wed Oct 30 18:33:58 2013] [notice] caught SIGTERM, shutting down
[Wed Oct 30 18:33:59 2013] [notice] Apache/2.2.16 (Debian) mod_wsgi/3.3 
Python/2.6.6 configured -- resuming normal operations
[Wed Oct 30 18:34:03 2013] [error] wsgilog.log: Wed, 30 Oct 2013 
18:34:03 ERROR Server got itself in trouble
[Wed Oct 30 18:34:03 2013] [error] Traceback (most recent call last):
[Wed Oct 30 18:34:03 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 18:34:03 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 18:34:03 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 18:34:03 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 18:34:03 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 18:34:03 2013] [error]     assert handler._finished
[Wed Oct 30 18:34:03 2013] [error] AssertionError
[Wed Oct 30 18:34:03 2013] [error] Server got itself in trouble
[Wed Oct 30 18:34:03 2013] [error] Traceback (most recent call last):
[Wed Oct 30 18:34:03 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 18:34:03 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 18:34:03 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 18:34:03 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 18:34:03 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 18:34:03 2013] [error]     assert handler._finished
[Wed Oct 30 18:34:03 2013] [error] AssertionError
[Wed Oct 30 18:34:03 2013] [error] /usr/lib/python2.6/cgitb.py:173: 
DeprecationWarning: BaseException.message has been deprecated as of 
Python 2.6
[Wed Oct 30 18:34:03 2013] [error]   value = 
pydoc.html.repr(getattr(evalue, name))
[Wed Oct 30 18:34:32 2013] [notice] caught SIGTERM, shutting down
[Wed Oct 30 18:35:14 2013] [notice] Apache/2.2.16 (Debian) mod_wsgi/3.3 
Python/2.6.6 configured -- resuming normal operations
[Wed Oct 30 18:36:41 2013] [error] wsgilog.log: Wed, 30 Oct 2013 
18:36:41 ERROR Server got itself in trouble
[Wed Oct 30 18:36:41 2013] [error] Traceback (most recent call last):
[Wed Oct 30 18:36:41 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 18:36:41 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 18:36:41 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 18:36:41 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 18:36:41 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 18:36:41 2013] [error]     assert handler._finished
[Wed Oct 30 18:36:41 2013] [error] AssertionError
[Wed Oct 30 18:36:41 2013] [error] Server got itself in trouble
[Wed Oct 30 18:36:41 2013] [error] Traceback (most recent call last):
[Wed Oct 30 18:36:41 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 18:36:41 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 18:36:41 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 18:36:41 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 18:36:41 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 18:36:41 2013] [error]     assert handler._finished
[Wed Oct 30 18:36:41 2013] [error] AssertionError
[Wed Oct 30 18:36:42 2013] [error] /usr/lib/python2.6/cgitb.py:173: 
DeprecationWarning: BaseException.message has been deprecated as of 
Python 2.6
[Wed Oct 30 18:36:42 2013] [error]   value = 
pydoc.html.repr(getattr(evalue, name))
[Wed Oct 30 18:41:15 2013] [notice] caught SIGTERM, shutting down
[Wed Oct 30 18:41:16 2013] [notice] Apache/2.2.16 (Debian) mod_wsgi/3.3 
Python/2.6.6 configured -- resuming normal operations
[Wed Oct 30 18:41:20 2013] [error] wsgilog.log: Wed, 30 Oct 2013 
18:41:20 ERROR Server got itself in trouble
[Wed Oct 30 18:41:20 2013] [error] Traceback (most recent call last):
[Wed Oct 30 18:41:20 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 18:41:20 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 18:41:20 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 18:41:20 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 18:41:20 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 18:41:20 2013] [error]     assert handler._finished
[Wed Oct 30 18:41:20 2013] [error] AssertionError
[Wed Oct 30 18:41:20 2013] [error] Server got itself in trouble
[Wed Oct 30 18:41:20 2013] [error] Traceback (most recent call last):
[Wed Oct 30 18:41:20 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 18:41:20 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 18:41:20 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 18:41:20 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 18:41:20 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 18:41:20 2013] [error]     assert handler._finished
[Wed Oct 30 18:41:20 2013] [error] AssertionError
[Wed Oct 30 18:41:21 2013] [error] /usr/lib/python2.6/cgitb.py:173: 
DeprecationWarning: BaseException.message has been deprecated as of 
Python 2.6
[Wed Oct 30 18:41:21 2013] [error]   value = 
pydoc.html.repr(getattr(evalue, name))
[Wed Oct 30 19:37:42 2013] [error] wsgilog.log: Wed, 30 Oct 2013 
19:37:42 ERROR Server got itself in trouble
[Wed Oct 30 19:37:42 2013] [error] Traceback (most recent call last):
[Wed Oct 30 19:37:42 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 19:37:42 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 19:37:42 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 19:37:42 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 19:37:42 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 19:37:42 2013] [error]     assert handler._finished
[Wed Oct 30 19:37:42 2013] [error] AssertionError
[Wed Oct 30 19:37:42 2013] [error] Server got itself in trouble
[Wed Oct 30 19:37:42 2013] [error] Traceback (most recent call last):
[Wed Oct 30 19:37:42 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 19:37:42 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 19:37:42 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 19:37:42 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 19:37:42 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 19:37:42 2013] [error]     assert handler._finished
[Wed Oct 30 19:37:42 2013] [error] AssertionError
[Wed Oct 30 19:37:42 2013] [error] /usr/lib/python2.6/cgitb.py:173: 
DeprecationWarning: BaseException.message has been deprecated as of 
Python 2.6
[Wed Oct 30 19:37:42 2013] [error]   value = 
pydoc.html.repr(getattr(evalue, name))
[Wed Oct 30 19:41:21 2013] [error] [client xxx.xxx.xxx.xxx] script not 
found or unable to stat: /usr/lib/cgi-bin/x2gobroker.cgi
[Wed Oct 30 19:42:29 2013] [error] wsgilog.log: Wed, 30 Oct 2013 
19:42:29 ERROR Server got itself in trouble
[Wed Oct 30 19:42:29 2013] [error] Traceback (most recent call last):
[Wed Oct 30 19:42:29 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 19:42:29 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 19:42:29 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 19:42:29 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 19:42:29 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 19:42:29 2013] [error]     assert handler._finished
[Wed Oct 30 19:42:29 2013] [error] AssertionError
[Wed Oct 30 19:42:29 2013] [error] Server got itself in trouble
[Wed Oct 30 19:42:29 2013] [error] Traceback (most recent call last):
[Wed Oct 30 19:42:29 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Wed Oct 30 19:42:29 2013] [error]     return self.application(environ, 
start_response)
[Wed Oct 30 19:42:29 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Wed Oct 30 19:42:29 2013] [error]     return 
_tornado_application(environ, start_response)
[Wed Oct 30 19:42:29 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Wed Oct 30 19:42:29 2013] [error]     assert handler._finished
[Wed Oct 30 19:42:29 2013] [error] AssertionError
[Wed Oct 30 19:42:29 2013] [error] /usr/lib/python2.6/cgitb.py:173: 
DeprecationWarning: BaseException.message has been deprecated as of 
Python 2.6
[Wed Oct 30 19:42:29 2013] [error]   value = 
pydoc.html.repr(getattr(evalue, name))
[Thu Oct 31 07:02:03 2013] [error] wsgilog.log: Thu, 31 Oct 2013 
07:02:03 ERROR Server got itself in trouble
[Thu Oct 31 07:02:03 2013] [error] Traceback (most recent call last):
[Thu Oct 31 07:02:03 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Thu Oct 31 07:02:03 2013] [error]     return self.application(environ, 
start_response)
[Thu Oct 31 07:02:03 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Thu Oct 31 07:02:03 2013] [error]     return 
_tornado_application(environ, start_response)
[Thu Oct 31 07:02:03 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Thu Oct 31 07:02:03 2013] [error]     assert handler._finished
[Thu Oct 31 07:02:03 2013] [error] AssertionError
[Thu Oct 31 07:02:03 2013] [error] Server got itself in trouble
[Thu Oct 31 07:02:03 2013] [error] Traceback (most recent call last):
[Thu Oct 31 07:02:03 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/wsgilog/__init__.py&quot;, line 179, in 
__call__
[Thu Oct 31 07:02:03 2013] [error]     return self.application(environ, 
start_response)
[Thu Oct 31 07:02:03 2013] [error]   File &quot;/usr/bin/x2gobroker&quot;, line 
243, in _application
[Thu Oct 31 07:02:03 2013] [error]     return 
_tornado_application(environ, start_response)
[Thu Oct 31 07:02:03 2013] [error]   File 
&quot;/usr/lib/python2.6/dist-packages/tornado/wsgi.py&quot;, line 94, in __call__
[Thu Oct 31 07:02:03 2013] [error]     assert handler._finished
[Thu Oct 31 07:02:03 2013] [error] AssertionError
[Thu Oct 31 07:02:03 2013] [error] /usr/lib/python2.6/cgitb.py:173: 
DeprecationWarning: BaseException.message has been deprecated as of 
Python 2.6
[Thu Oct 31 07:02:03 2013] [error]   value = 
pydoc.html.repr(getattr(evalue, name))





On 10/30/13 11:00, <A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">x2go-user-request at lists.berlios.de</A> wrote:
&gt;<i> Send X2Go-User mailing list submissions to
</I>&gt;<i> 	<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">x2go-user at lists.berlios.de</A>
</I>&gt;<i>
</I>&gt;<i> To subscribe or unsubscribe via the World Wide Web, visit
</I>&gt;<i> 	<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">https://lists.berlios.de/mailman/listinfo/x2go-user</A>
</I>&gt;<i> or, via email, send a message with subject or body 'help' to
</I>&gt;<i> 	<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">x2go-user-request at lists.berlios.de</A>
</I>&gt;<i>
</I>&gt;<i> You can reach the person managing the list at
</I>&gt;<i> 	<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">x2go-user-owner at lists.berlios.de</A>
</I>&gt;<i>
</I>&gt;<i> When replying, please edit your Subject line so it is more specific
</I>&gt;<i> than &quot;Re: Contents of X2Go-User digest...&quot;
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> Today's Topics:
</I>&gt;<i>
</I>&gt;<i>     1. X2Go-User] x2go  connect problem (Coen, Kay L)
</I>&gt;<i>     2. Re: X2Go-User] x2go connect problem (Mike Gabriel)
</I>&gt;<i>     3. Re: X2Go-User Digest, Vol 38, Issue 25 (Ted Barnes)
</I>&gt;<i>     4. session broker setup (was: Re:  X2Go-User Digest, Vol 38,
</I>&gt;<i>        Issue 25) (Mike Gabriel)
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> ----------------------------------------------------------------------
</I>&gt;<i>
</I>&gt;<i> Message: 1
</I>&gt;<i> Date: Tue, 29 Oct 2013 14:28:14 +0000
</I>&gt;<i> From: &quot;Coen, Kay L&quot;&lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">coen at lanl.gov</A>&gt;
</I>&gt;<i> To: &quot;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">x2go-user at lists.berlios.de</A>&quot;&lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">x2go-user at lists.berlios.de</A>&gt;
</I>&gt;<i> Subject: [X2Go-User] X2Go-User] x2go  connect problem
</I>&gt;<i> Message-ID:&lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">D4899739-211B-4E68-A5A3-FBC350F9829F at lanl.gov</A>&gt;
</I>&gt;<i> Content-Type: text/plain; charset=&quot;us-ascii&quot;
</I>&gt;<i>
</I>&gt;<i> I am using X2Go, version  X2Go client V. 3.99.2.1 (Qt - 4.7.4) on a Mac, OS X 10.7.5.  When I attempt to a RHEL6 server I receive the following error message:   Connection failed export: Command not found
</I>&gt;<i>
</I>&gt;<i> Doe anyone have any ideas on how to get X2Go working.
</I>&gt;<i>
</I>&gt;<i> Thank you!
</I>&gt;<i>
</I>&gt;<i> Kay Coen
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> ------------------------------
</I>&gt;<i>
</I>&gt;<i> Message: 2
</I>&gt;<i> Date: Tue, 29 Oct 2013 14:57:27 +0000
</I>&gt;<i> From: Mike Gabriel&lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">mike.gabriel at das-netzwerkteam.de</A>&gt;
</I>&gt;<i> To: <A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">x2go-user at lists.berlios.de</A>
</I>&gt;<i> Subject: Re: [X2Go-User] X2Go-User] x2go connect problem
</I>&gt;<i> Message-ID:
</I>&gt;<i> 	&lt;<A HREF="https://lists.berlios.de/mailman/listinfo/x2go-user">20131029145727.Horde.B-TA07F5aKcs6gRwSL5Ltw1 at mail.das-netzwerkteam.de</A>&gt;
</I>&gt;<i> 	
</I>&gt;<i> Content-Type: text/plain; charset=&quot;utf-8&quot;; Format=&quot;flowed&quot;;
</I>&gt;<i> 	DelSp=&quot;Yes&quot;
</I>&gt;<i>
</I>&gt;<i> On  Di 29 Okt 2013 15:28:14 CET, Coen, Kay L wrote:
</I>&gt;<i>
</I>&gt;<i>    
</I>&gt;&gt;<i> I am using X2Go, version  X2Go client V. 3.99.2.1 (Qt - 4.7.4) on a
</I>&gt;&gt;<i> Mac, OS X 10.7.5.  When I attempt to a RHEL6 server I receive the
</I>&gt;&gt;<i> following error message:   Connection failed export: Command not found
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Doe anyone have any ideas on how to get X2Go working.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Thank you!
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Kay Coen
</I>&gt;&gt;<i>      
</I>&gt;<i> How about installing X2Go Server on the machine you want to connect to?
</I>&gt;<i>
</I>&gt;<i> If X2Go Server is installed, make sure the desktop shell you aim at
</I>&gt;<i> using is installed on that machine, as well.
</I>&gt;<i>
</I>&gt;<i> Also, I have heard several people having problems with X2Go on RHEL6.
</I>&gt;<i> Fedora 19+20 are the best supported RPM based distros atm.
</I>&gt;<i>
</I>&gt;<i> Mike
</I>&gt;<i>    
</I>
</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="001737.html">[X2Go-User] session broker setup (was: Re:  X2Go-User Digest, Vol 38, Issue 25)
</A></li>
	<LI>Next message: <A HREF="001739.html">[X2Go-User] X2Go-User Non-Digest, Vol 38, Issue 26
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1738">[ date ]</a>
              <a href="thread.html#1738">[ thread ]</a>
              <a href="subject.html#1738">[ subject ]</a>
              <a href="author.html#1738">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/x2go-user">More information about the X2Go-User
mailing list</a><br>
</body></html>
